"""
Django settings for bookaid project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import json
import boto3
from celery.schedules import crontab
from dotenv import load_dotenv


def load_secrets(secret_name=None, region="us-east-1"):
    if secret_name is None:
        secret_name = get_env('secret_name')
    client = boto3.client("secretsmanager", region_name=region)
    response = client.get_secret_value(SecretId=secret_name)
    return json.loads(response["SecretString"])

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR / '.env'
load_dotenv(ENV_FILE)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Real servers (EC2 instances) are provisioned without a .env file at all and
# pull every config value from AWS Secrets Manager instead; only a local
# checkout has a .env file, so its presence is what tells the two apart —
# DEBUG can't be used for this (a real server may still run DEBUG=True).
USE_SECRETS_MANAGER = not ENV_FILE.exists()
secrets = load_secrets() if USE_SECRETS_MANAGER else {}


def get_env(key, default=None):
    if USE_SECRETS_MANAGER:
        return secrets.get(key, default)
    return os.getenv(key, default)


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('SECRET_KEY', 'django-insecure-+m!dtn=()j@rs%01t#c^c&(s3lku25v$+avwnzy$an73tq+t#p')

ALLOWED_HOSTS = get_env('ALLOWED_HOSTS', '*').split(',')

# Google Analytics (GA4) — only sent to templates when DEBUG is off, so local
# development traffic doesn't pollute production analytics.
GOOGLE_ANALYTICS_ID = get_env('GOOGLE_ANALYTICS_ID', '')

# The CountryAndState admin list (and other large tables) can have several
# thousand rows selected at once via "select all across pages" bulk actions,
# which POSTs one field per selected row. Django's default cap (1000) is too
# low for that, so raise it well above our largest table's row count.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000
CORS_ALLOW_ALL_ORIGINS = True
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
CSRF_TRUSTED_ORIGINS = [

    'https://dev.favhost.com',
    # 'http://34.207.186.12:8000',
    'http://107.22.56.63:8000',
    'http://98.85.225.195:8000',    
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'http://favhost.com',
    'https://favhost.com',
    'https://dev.favhost.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Trust the X-Forwarded-Proto header set by nginx / the load balancer so
# Django knows the original request was HTTPS (request.scheme, request.build_absolute_uri(),
# etc. all depend on this). Kept outside the `if not DEBUG` block below because
# dev.favhost.com runs with DEBUG=True but is still behind an HTTPS-terminating
# proxy — same reasoning as AWS_STORAGE_BUCKET_NAME above, DEBUG alone can't
# tell "behind a proxy" apart from "plain local runserver". Harmless locally:
# a direct connection to runserver never sends this header, so request.scheme
# just reflects the real (http) connection as before.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ── Production security hardening (only active when DEBUG=False) ──
# Kept off in local dev so plain http://localhost keeps working.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True



# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # third party
    'rest_framework',

    #apps
    'accounts',
    'property',
    'booking',
    'tasks',
    'global',
    'billing',
    'printpanel',
    'frontdesk',
    'shared',
    'storages',

    # Hidden platform-owner admin console (separate from Django's /admin/).
    'controlpanel',

]

AUTH_USER_MODEL = 'accounts.MyUser'

AUTHENTICATION_BACKENDS = ['accounts.backends.EmailOrUsernameBackend']


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Renders our branded 404.html for missing URLs even when DEBUG=True.
    'bookaid.middleware.CustomPageNotFoundMiddleware',

    # Prevents browsers caching authenticated HTML pages, so the subscription
    # paywall is re-checked on every navigation (not only on a hard refresh).
    'bookaid.middleware.NoCacheAuthenticatedHTMLMiddleware',
]

ROOT_URLCONF = 'bookaid.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'property.context_processors.property_context',
                'bookaid.context_processors.enquiry_counts',
                'bookaid.context_processors.google_analytics',
                'billing.context_processors.subscription_status',
                'accounts.context_processors.currency_context',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookaid.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': get_env('DB_ENGINE', 'django.db.backends.postgresql_psycopg2'),
        'NAME': get_env('DB_NAME', 'favhost'),
        'USER': get_env('DB_USER', 'postgres'),
        'PASSWORD': get_env('DB_PASSWORD', 'postgres'),
        'HOST': get_env('DB_HOST', '127.0.0.1'),
        'PORT': get_env('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Celery Settings
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'  # Requires Redis server running
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    'sync-bookings-every-4-hours': {
        'task': 'booking.utils.trigger_sync_all_channels',
        # 'schedule': crontab(minute=0, hour='*/4'),  # Runs at minute 0 past every 4th hour
        # 'schedule': crontab(minute='*/2'),  # Runs at minute 0 past every 4th hour
        'schedule': crontab(minute='*/15'),  # Runs every 15 minutes
    },
    # Runs every hour at :01. The task itself decides which properties are at
    # their local midnight, so guests are emailed at the *hotel's* midnight
    # regardless of country/timezone.
    'send-booking-emails-hourly': {
        'task': 'booking.tasks.send_daily_booking_emails',
        'schedule': crontab(minute=1),  # every hour at HH:01
    },
    'refresh-exchange-rates-daily': {
        'task': 'accounts.tasks.refresh_exchange_rates_task',
        'schedule': crontab(minute=30, hour=0),  # Runs daily at 12:30 AM
    },
}

SESSION_COOKIE_AGE = 3600  # 60 minutes
SESSION_SAVE_EVERY_REQUEST = True  # Session expires after 30 minutes of inactivity.
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

# Which storage backend to use is decided by AWS_STORAGE_BUCKET_NAME, not
# DEBUG — dev.favhost.com runs with DEBUG=True but still needs S3, so DEBUG
# alone can't tell "your laptop" apart from "a real server". Each server's
# own .env sets this to its bucket (favhost-media-dev / favhost-media-prod);
# a local checkout simply leaves it unset and falls back to disk.
AWS_STORAGE_BUCKET_NAME = get_env('AWS_STORAGE_BUCKET_NAME')

if AWS_STORAGE_BUCKET_NAME:
    AWS_S3_REGION_NAME = "us-east-1"

    # No AWS_S3_CUSTOM_DOMAIN here on purpose: django-storages always returns
    # an unsigned URL for a custom domain, ignoring AWS_QUERYSTRING_AUTH below
    # — that only works against a public bucket, which these are not. Without
    # a custom domain, it builds a proper signed (presigned) S3 URL instead,
    # using the EC2 instance's IAM role credentials, so the bucket can stay
    # private.
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600  # seconds a signed media URL stays valid

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    # Local machine: no bucket configured, media lives on disk so no AWS
    # credentials are needed and nobody touches a real bucket by accident.
    MEDIA_ROOT = BASE_DIR / 'media'
    MEDIA_URL = '/media/'

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }



# Email Settings
EMAIL_BACKEND = get_env('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = get_env('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(get_env('EMAIL_PORT', 587))
EMAIL_USE_TLS = get_env('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = get_env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = get_env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = get_env('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
# Address used for Reply-To and the List-Unsubscribe mailto on outgoing emails.
SUPPORT_EMAIL = get_env('SUPPORT_EMAIL', 'support@favhost.com')

# --- Dedicated Zoho SMTP for the public contact form ---------------------- #
# The default EMAIL_* account above (Namecheap/noreply) keeps sending every
# other platform email. The contact form uses this separate Zoho account so
# messages are delivered straight into the support@favhost.com inbox.
SUPPORT_EMAIL_HOST = get_env('SUPPORT_EMAIL_HOST', 'smtp.zoho.com')
SUPPORT_EMAIL_PORT = int(get_env('SUPPORT_EMAIL_PORT', 587))
SUPPORT_EMAIL_USE_TLS = get_env('SUPPORT_EMAIL_USE_TLS', 'True') == 'True'
SUPPORT_EMAIL_HOST_USER = get_env('SUPPORT_EMAIL_HOST_USER', SUPPORT_EMAIL)
SUPPORT_EMAIL_HOST_PASSWORD = get_env('SUPPORT_EMAIL_HOST_PASSWORD')

# --- Tutorials / YouTube channel ---
# Set this to your real YouTube channel (or on-site tutorials page) URL.
# Used by the "Watch tutorials" button in the welcome email.
TUTORIALS_URL = get_env('TUTORIALS_URL', 'https://www.youtube.com/@YOUR_CHANNEL')

# --- Stripe Configuration ---
STRIPE_PUBLISHABLE_KEY = get_env('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = get_env('STRIPE_SECRET_KEY', '')
STRIPE_PRICE_ID = get_env('STRIPE_PRICE_ID', '')
STRIPE_PRICE_ID_YEARLY = get_env('STRIPE_PRICE_ID_YEARLY', '')
STRIPE_WEBHOOK_SECRET = get_env('STRIPE_WEBHOOK_SECRET', '')
DOMAIN_URL = get_env('DOMAIN_URL', 'http://localhost:8000')

# --- Firebase Configuration ---
FIREBASE_API_KEY = get_env('FIREBASE_API_KEY', '')
FIREBASE_AUTH_DOMAIN = get_env('FIREBASE_AUTH_DOMAIN', '')
FIREBASE_PROJECT_ID = get_env('FIREBASE_PROJECT_ID', '')
FIREBASE_STORAGE_BUCKET = get_env('FIREBASE_STORAGE_BUCKET', '')
FIREBASE_MESSAGING_SENDER_ID = get_env('FIREBASE_MESSAGING_SENDER_ID', '')
FIREBASE_APP_ID = get_env('FIREBASE_APP_ID', '')
FIREBASE_MEASUREMENT_ID = get_env('FIREBASE_MEASUREMENT_ID', '')
FIREBASE_ADMIN_PRIVATE_KEY = get_env('FIREBASE_ADMIN_PRIVATE_KEY', '')
FIREBASE_ADMIN_CLIENT_EMAIL = get_env('FIREBASE_ADMIN_CLIENT_EMAIL', '')

# Google Identity Services (GIS) — used for "Continue with Google".
# This is the OAuth 2.0 Web client ID from Google Cloud Console (the same one
# Firebase auto-created for this project). GIS avoids the Firebase redirect flow
# that breaks on iOS due to WebKit storage partitioning.
GOOGLE_OAUTH_CLIENT_ID = get_env('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_MAPS_API_KEY = get_env('GOOGLE_MAPS_API_KEY', '')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


JAZZMIN_SETTINGS = {
    "site_title": "Bookaid Admin",
    "site_header": "Bookaid Admin",
    # "show_dashboard": False,  
    # "show_sidebar": True,
    # "navigation_expanded": True,

    
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'frontdesk:index'
LOGOUT_REDIRECT_URL = 'login'

# ── Hidden platform-owner admin console (controlpanel app) ──
# The console lives at /console/ and is locked to exactly ONE predefined
# account — no other user can ever reach it, regardless of is_staff/is_admin.
# Change the email here (or via the env var) if the owner account changes.
PLATFORM_ADMIN_EMAIL = os.getenv('PLATFORM_ADMIN_EMAIL', 'bookaid@gmail.com')
PLATFORM_ADMIN_DEFAULT_PASSWORD = os.getenv('PLATFORM_ADMIN_PASSWORD', 'bookaid123')

# Base URL for generating absolute URLs in emails
BASE_URL = get_env('BASE_URL', 'http://favhost.com')

# Allow same-origin framing (needed for detail modal on list page)
X_FRAME_OPTIONS = 'SAMEORIGIN'
