# Generated by Django 5.2.5 on 2026-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAndState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=150)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country_short', models.CharField(blank=True, max_length=10, null=True)),
                ('state_name', models.CharField(blank=True, max_length=150, null=True)),
                ('state_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['country_name', 'state_name'],
            },
        ),
    ]
