# Generated by Django 5.2.5 on 2026-06-19 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Only for Admin', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Only for Admin', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(default='USD', help_text='Preferred currency for transactions', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, null=True)),
                ('short_code', models.CharField(blank=True, help_text='Unique alphanumeric code for public URLs', max_length=20, null=True, unique=True)),
                ('instagram_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin panel and perform all types of actions.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin panel.')),
                ('timezone', models.CharField(default='America/New_York', help_text="User's timezone for date/time calculations", max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('language', models.CharField(blank=True, default='English', max_length=100, null=True)),
                ('is_subscription_free', models.BooleanField(default=False, help_text='If enabled, user gets free access without requiring subscription payment')),
                ('trial_ending_email_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='user_documents/')),
                ('doc_type', models.CharField(choices=[('govt_id', 'Government ID'), ('permission', 'Local Authority Permission')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_password', models.CharField(blank=True, help_text='Plain text password for UI display only', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('co_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_host_relationships', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_cohosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('host', 'co_host')},
            },
        ),
    ]
