# Generated by Django 5.2.5 on 2026-07-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='other_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Other fees'),
        ),
        migrations.AddField(
            model_name='booking',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxes'),
        ),
    ]
