# Generated by Django 5.2.5 on 2026-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(max_length=300)),
                ('visitor_key', models.CharField(db_index=True, max_length=32)),
                ('referrer_host', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'page view',
                'indexes': [models.Index(fields=['created_at', 'visitor_key'], name='controlpane_created_41f96c_idx'), models.Index(fields=['created_at', 'path'], name='controlpane_created_7680aa_idx')],
            },
        ),
    ]
