# Generated by Django 5.2.5 on 2026-07-02 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0005_property_rental_contract_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Dirty', 'Dirty'), ('In-Progress', 'In-Progress'), ('Clean-Uninspected', 'Clean-Uninspected'), ('Clean-Inspected', 'Clean-Inspected'), ('Clean-Ready', 'Clean-Ready'), ('Out-of-Service', 'Out-of-Service')], default='Clean-Inspected', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hk_status', to='property.property')),
            ],
        ),
    ]
