# Generated by Django 5.2.5 on 2026-07-09 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0002_housekeepingstatus_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeepingstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Dirty', 'Dirty'), ('In-Progress', 'In-Progress'), ('Clean-Uninspected', 'Clean-Uninspected'), ('Clean-Inspected', 'Clean-Inspected'), ('Clean-Ready', 'Clean-Ready'), ('Out-of-Service', 'Out-of-Service')], default=None, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('created_by', 'name')},
            },
        ),
        migrations.AddField(
            model_name='housekeepingstatus',
            name='cleaner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='frontdesk.cleaner'),
        ),
    ]
