# Generated by Django 5.2.5 on 2026-07-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0003_alter_housekeepingstatus_status_cleaner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
