# Generated by Django 5.2.5 on 2026-06-19 20:10

import django.db.models.deletion
import property.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='amenities/icons/', validators=[property.models.validate_amenity_icon])),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('guest', models.PositiveIntegerField(default=1, verbose_name='Number of Guests (max)')),
                ('bathroom_type', models.CharField(choices=[('', 'Select'), ('Private', 'Private'), ('Shared', 'Shared')], max_length=20)),
                ('property_type', models.CharField(choices=[('', 'Select'), ('entire_place', 'An entire place'), ('private_room', 'Private room  (Shared House)'), ('shared_room', 'Shared room in a hostel')], max_length=20)),
                ('bed_type', models.CharField(choices=[('', 'Select'), ('King', 'King Bed'), ('Queen', 'Queen Bed'), ('Full', 'Full Bed'), ('Twin', 'Twin Bed')], max_length=20)),
                ('status', models.CharField(choices=[('', 'Select'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('room_password', models.CharField(blank=True, max_length=100, null=True)),
                ('network_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wifi_password', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum_booking', models.PositiveIntegerField(default=1, verbose_name='Minimum Booking (nights)')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('check_in_time', models.TimeField(default='15:00')),
                ('check_out_time', models.TimeField(default='10:00')),
                ('email_guest', models.BooleanField(default=False, verbose_name='Email guest before Check-in')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Cancellation, Other Policies and Rules')),
                ('house_rules', models.TextField(blank=True, null=True, verbose_name='House Rules')),
                ('cancellation_policy', models.TextField(blank=True, null=True, verbose_name='Cancellation Policy')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price/Night')),
                ('application_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('cleaning_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('refundable_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('ical_token', models.UUIDField(default=uuid.uuid4, help_text='Unique token for iCal feed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='property.amenities')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyBlockDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('external_uid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_link', models.URLField(max_length=1000)),
                ('is_connected', models.BooleanField(default=True)),
                ('channel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingchannel')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_channels', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='property_documents/')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(choices=[('check_in', 'Check-in Instruction'), ('check_out', 'Check-out Instruction')], default='check_in', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
