# Generated by Django 5.2.5 on 2026-06-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Code'),
        ),
        migrations.AddField(
            model_name='property',
            name='nick_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nick Name'),
        ),
        migrations.AddField(
            model_name='property',
            name='other_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Other Fees'),
        ),
        migrations.AddField(
            model_name='property',
            name='taxes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Taxes'),
        ),
    ]
