# Generated by Django 5.2.5 on 2026-06-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_add_nick_name_country_code_taxes_other_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='country_code',
        ),
    ]
