# Generated by Django 5.2.5 on 2026-06-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_application_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rental_contract_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Rental Contract Terms and Conditions'),
        ),
    ]
