# Generated by Django 5.2.5 on 2026-10-03 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_notification'),
        ('property', '0006_property_email_guest_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyblockdate',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_dates', to='booking.bookingchannel'),
        ),
    ]
